language: node_js
env:
  - NODE_ENV=production DB_NAME=d3r5c6vtp4t096 DB_USERNAME=gptbgajiaaighp DB_PASSWORD=b7df45ceb2bec1f6a177f1482287837b520b07ed7123c1ad3b5e8aef84f9dc7e DB_HOST=ec2-23-21-229-200.compute-1.amazonaws.com
node_js:
  - "8"
script:
  - npm install
  - npm run db:migrate 